- name: Install Dependencies & Fixed Pip
      run: |
        python -m pip install --upgrade setuptools wheel
        # Pip ko 23.0.1 par pin kar rahe hain taaki p4a ke saath error na aaye
        python -m pip install "pip==23.0.1"
        python -m pip install "cython==0.29.33" "buildozer==1.5.0"
        python -m pip install "git+https://github.com/kivy/python-for-android.git"
